/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0L9ehSbQqzY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Tenor_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { ChartTooltipContent, ChartTooltip, ChartContainer } from "@/components/ui/chart"
import { Pie, PieChart, CartesianGrid, XAxis, Line, LineChart } from "recharts"

export function main_porfolio() {
  return (
    <div className="bg-background text-foreground">
      <header className="container mx-auto py-8 px-4 md:py-12 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">John Doe</h1>
          <p className="max-w-[600px] text-muted-foreground md:text-xl">
            Experienced web developer and data analyst passionate about creating innovative solutions.
          </p>
          <div className="flex items-center gap-2 text-sm">
            <MailOpenIcon className="h-4 w-4" />
            <a href="#" className="underline underline-offset-4">
              javiersvadillo@gmail.com
            </a>
          </div>
        </div>
      </header>
      <section className="container mx-auto py-12 px-4 md:py-16 md:px-6">
        <div className="grid gap-8 md:grid-cols-2">
          <div>
            <h2 className="mb-4 text-2xl font-bold">Skills</h2>
            <div className="grid gap-6">
              <div>
                <h3 className="mb-2 text-lg font-semibold">Web Development</h3>
                <PiechartcustomChart className="aspect-square" />
              </div>
              <div>
                <h3 className="mb-2 text-lg font-semibold">Data Analysis</h3>
                <PiechartcustomChart className="aspect-[3/2]" />
              </div>
            </div>
          </div>
          <div>
            <h2 className="mb-4 text-2xl font-bold">Projects</h2>
            <div className="grid gap-6">
              <div>
                <img
                  src="/placeholder.svg"
                  width="300"
                  height="200"
                  alt="Project 1"
                  className="mb-2 rounded-lg"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <h3 className="mb-1 text-lg font-semibold">Project 1</h3>
                <p className="text-muted-foreground">
                  A responsive web application built with React and Node.js, featuring a modern design and intuitive
                  user experience.
                </p>
              </div>
              <div>
                <img
                  src="/placeholder.svg"
                  width="300"
                  height="200"
                  alt="Project 2"
                  className="mb-2 rounded-lg"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <h3 className="mb-1 text-lg font-semibold">Project 2</h3>
                <p className="text-muted-foreground">
                  A data visualization dashboard built with Python and Tableau, providing insights into complex business
                  data.
                </p>
              </div>
              <div>
                <img
                  src="/placeholder.svg"
                  width="300"
                  height="200"
                  alt="Project 3"
                  className="mb-2 rounded-lg"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <h3 className="mb-1 text-lg font-semibold">Project 3</h3>
                <p className="text-muted-foreground">
                  A machine learning model developed with Python and TensorFlow, used for predictive analytics in the
                  finance industry.
                </p>
              </div>
              <Button variant="outline" className="mx-auto">
                See more
              </Button>
            </div>
          </div>
        </div>
      </section>
      <section className="container mx-auto py-12 px-4 md:py-16 md:px-6">
        <div className="grid gap-8 md:grid-cols-2">
          <div>
            <h2 className="mb-4 text-2xl font-bold">Experience</h2>
            <div className="grid gap-6">
              <div>
                <h3 className="mb-2 text-lg font-semibold">Web Developer</h3>
                <p className="text-muted-foreground">Acme Inc. | 2018 - Present</p>
                <p className="text-muted-foreground">
                  Developed and maintained responsive web applications using React, Node.js, and various front-end and
                  back-end technologies. Collaborated with cross-functional teams to deliver high-quality, user-centric
                  solutions.
                </p>
              </div>
              <div>
                <h3 className="mb-2 text-lg font-semibold">Data Analyst</h3>
                <p className="text-muted-foreground">XYZ Corporation | 2015 - 2018</p>
                <p className="text-muted-foreground">
                  Analyzed complex business data using Python, SQL, and data visualization tools. Provided insights and
                  recommendations to help drive strategic decision-making.
                </p>
              </div>
            </div>
          </div>
          <div>
            <h2 className="mb-4 text-2xl font-bold">Education</h2>
            <div className="grid gap-6">
              <div>
                <h3 className="mb-2 text-lg font-semibold">Bachelor of Science in Computer Science</h3>
                <p className="text-muted-foreground">University of Technology | 2011 - 2015</p>
              </div>
              <div>
                <h3 className="mb-2 text-lg font-semibold">Master of Science in Data Analytics</h3>
                <p className="text-muted-foreground">University of Data | 2015 - 2017</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <footer className="bg-muted py-6 text-center text-muted-foreground">
        <p>&copy; 2024 John Doe. All rights reserved.</p>
      </footer>
    </div>
  )
}

function LinechartChart(props:any) {
  return (
    <div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}
      >
        <LineChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
          margin={{
            left: 12,
            right: 12,
          }}
        >
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            axisLine={false}
            tickMargin={8}
            tickFormatter={(value) => value.slice(0, 3)}
          />
          <ChartTooltip cursor={false} content={<ChartTooltipContent hideLabel />} />
          <Line dataKey="desktop" type="natural" stroke="var(--color-desktop)" strokeWidth={2} dot={false} />
        </LineChart>
      </ChartContainer>
    </div>
  )
}


function MailOpenIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.2 8.4c.5.38.8.97.8 1.6v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V10a2 2 0 0 1 .8-1.6l8-6a2 2 0 0 1 2.4 0l8 6Z" />
      <path d="m22 10-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 10" />
    </svg>
  )
}


function PiechartcustomChart(props:any) {
  return (
    <div {...props}>
      <ChartContainer
        config={{
          visitors: {
            label: "Visitors",
          },
          chrome: {
            label: "Chrome",
            color: "hsl(var(--chart-1))",
          },
          safari: {
            label: "Safari",
            color: "hsl(var(--chart-2))",
          },
          firefox: {
            label: "Firefox",
            color: "hsl(var(--chart-3))",
          },
          edge: {
            label: "Edge",
            color: "hsl(var(--chart-4))",
          },
          other: {
            label: "Other",
            color: "hsl(var(--chart-5))",
          },
        }}
      >
        <PieChart>
          <ChartTooltip cursor={false} content={<ChartTooltipContent hideLabel />} />
          <Pie
            data={[
              { browser: "chrome", visitors: 275, fill: "var(--color-chrome)" },
              { browser: "safari", visitors: 200, fill: "var(--color-safari)" },
              { browser: "firefox", visitors: 187, fill: "var(--color-firefox)" },
              { browser: "edge", visitors: 173, fill: "var(--color-edge)" },
              { browser: "other", visitors: 90, fill: "var(--color-other)" },
            ]}
            dataKey="visitors"
            nameKey="browser"
          />
        </PieChart>
      </ChartContainer>
    </div>
  )
}
